use core::fmt;

use crate::math::{Mat4, multiply};
use crate::render_world::{GpuCamera, GpuInstance, RenderWorld};

#[derive(Clone, Copy, Debug, Default, PartialEq)]
struct Plane {
    normal: [f32; 3],
    distance: f32,
}

/// Six normalized clipping planes used for CPU sphere culling.
#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct Frustum {
    planes: [Plane; 6],
}

impl Frustum {
    /// Builds a frustum from an extracted camera's projection and view matrices.
    #[must_use]
    pub fn from_camera(camera: &GpuCamera) -> Self {
        let mut view_projection = Mat4::default();
        multiply(&mut view_projection, &camera.projection, &camera.view);
        Self::from_view_projection(&view_projection)
    }

    /// Builds a frustum from a column-major view-projection matrix.
    #[must_use]
    pub fn from_view_projection(matrix: &Mat4) -> Self {
        let m = &matrix.0;
        let row_0 = [m[0], m[4], m[8], m[12]];
        let row_1 = [m[1], m[5], m[9], m[13]];
        let row_2 = [m[2], m[6], m[10], m[14]];
        let row_3 = [m[3], m[7], m[11], m[15]];
        Self {
            planes: [
                plane_add(row_3, row_0),
                plane_subtract(row_3, row_0),
                plane_add(row_3, row_1),
                plane_subtract(row_3, row_1),
                normalized_plane(row_2),
                plane_subtract(row_3, row_2),
            ],
        }
    }

    /// Returns whether a sphere intersects or lies inside every clipping plane.
    #[must_use]
    pub fn intersects_sphere(&self, center: [f32; 3], radius: f32) -> bool {
        self.planes.iter().all(|plane| {
            plane.normal[0] * center[0]
                + plane.normal[1] * center[1]
                + plane.normal[2] * center[2]
                + plane.distance
                >= -radius
        })
    }
}

fn plane_add(left: [f32; 4], right: [f32; 4]) -> Plane {
    normalized_plane([
        left[0] + right[0],
        left[1] + right[1],
        left[2] + right[2],
        left[3] + right[3],
    ])
}

fn plane_subtract(left: [f32; 4], right: [f32; 4]) -> Plane {
    normalized_plane([
        left[0] - right[0],
        left[1] - right[1],
        left[2] - right[2],
        left[3] - right[3],
    ])
}

fn normalized_plane(values: [f32; 4]) -> Plane {
    let inverse_length =
        1.0 / (values[0] * values[0] + values[1] * values[1] + values[2] * values[2]).sqrt();
    Plane {
        normal: [
            values[0] * inverse_length,
            values[1] * inverse_length,
            values[2] * inverse_length,
        ],
        distance: values[3] * inverse_length,
    }
}

/// Counts generated by one [`VisibleRenderBuffer::cull`] operation.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct VisibilityStats {
    /// Number of render-world instances checked against the frustum.
    pub tested: usize,
    /// Number of instances retained in the visible buffers.
    pub visible: usize,
}

/// Fixed-capacity visibility failure; no output storage is reallocated.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct VisibilityError {
    /// Configured visible-instance capacity that was exceeded.
    pub capacity: usize,
}

impl fmt::Display for VisibilityError {
    fn fmt(&self, formatter: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            formatter,
            "VisibleRenderBuffer capacity exceeded ({})",
            self.capacity
        )
    }
}

/// Fixed-capacity, compact renderer input ordered by pipeline/material/mesh.
pub struct VisibleRenderBuffer {
    capacity: usize,
    source_indices: Vec<u32>,
    geometries: Vec<u32>,
    pipelines: Vec<u32>,
    materials: Vec<u32>,
    instances: Vec<GpuInstance>,
    bucket_heads: Vec<usize>,
    bucket_tails: Vec<usize>,
    bucket_pipelines: Vec<u32>,
    bucket_materials: Vec<u32>,
    bucket_geometries: Vec<u32>,
    source_next: Vec<usize>,
    active_buckets: Vec<usize>,
}

impl VisibleRenderBuffer {
    /// Allocates reusable buffers for at most `capacity` visible instances.
    #[must_use]
    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            capacity,
            source_indices: Vec::with_capacity(capacity),
            geometries: Vec::with_capacity(capacity),
            pipelines: Vec::with_capacity(capacity),
            materials: Vec::with_capacity(capacity),
            instances: Vec::with_capacity(capacity),
            bucket_heads: vec![usize::MAX; capacity],
            bucket_tails: vec![usize::MAX; capacity],
            bucket_pipelines: vec![0; capacity],
            bucket_materials: vec![0; capacity],
            bucket_geometries: vec![0; capacity],
            source_next: vec![usize::MAX; capacity],
            active_buckets: Vec::with_capacity(capacity),
        }
    }

    /// Culls, groups, and compacts `render_world` without per-frame allocation.
    ///
    /// The first camera supplies the frustum. With no camera, all instances are
    /// considered visible. Output is grouped by pipeline, material, and geometry.
    pub fn cull(&mut self, render_world: &RenderWorld) -> Result<VisibilityStats, VisibilityError> {
        self.clear();
        let frustum = render_world.cameras().first().map(Frustum::from_camera);
        for (index, bounds) in render_world.bounds().iter().enumerate() {
            let [x, y, z, radius] = bounds.center_radius;
            if frustum
                .as_ref()
                .is_none_or(|value| value.intersects_sphere([x, y, z], radius))
            {
                if self.source_indices.len() == self.capacity {
                    return Err(VisibilityError {
                        capacity: self.capacity,
                    });
                }
                self.push_source_index(render_world, index)?;
            }
        }

        self.active_buckets.sort_unstable_by_key(|bucket| {
            (
                self.bucket_pipelines[*bucket],
                self.bucket_materials[*bucket],
                self.bucket_geometries[*bucket],
            )
        });
        for bucket in self.active_buckets.iter().copied() {
            let mut entry = self.bucket_heads[bucket];
            while entry != usize::MAX {
                let index = self.source_indices[entry] as usize;
                self.geometries.push(render_world.geometries()[index]);
                self.pipelines.push(render_world.pipelines()[index]);
                self.materials.push(render_world.materials()[index]);
                self.instances.push(render_world.instances()[index]);
                entry = self.source_next[entry];
            }
        }

        Ok(VisibilityStats {
            tested: render_world.instances().len(),
            visible: self.instances.len(),
        })
    }

    /// Clears logical output and reusable grouping state without freeing memory.
    pub fn clear(&mut self) {
        for bucket in self.active_buckets.drain(..) {
            self.bucket_heads[bucket] = usize::MAX;
            self.bucket_tails[bucket] = usize::MAX;
        }
        self.source_indices.clear();
        self.geometries.clear();
        self.pipelines.clear();
        self.materials.clear();
        self.instances.clear();
    }

    fn push_source_index(
        &mut self,
        render_world: &RenderWorld,
        source_index: usize,
    ) -> Result<(), VisibilityError> {
        let pipeline = render_world.pipelines()[source_index];
        let material = render_world.materials()[source_index];
        let geometry = render_world.geometries()[source_index];
        let mut bucket = hash_render_key(pipeline, material, geometry) % self.capacity;
        loop {
            if self.bucket_heads[bucket] == usize::MAX {
                self.bucket_pipelines[bucket] = pipeline;
                self.bucket_materials[bucket] = material;
                self.bucket_geometries[bucket] = geometry;
                self.active_buckets.push(bucket);
                break;
            }
            if self.bucket_pipelines[bucket] == pipeline
                && self.bucket_materials[bucket] == material
                && self.bucket_geometries[bucket] == geometry
            {
                break;
            }
            bucket = (bucket + 1) % self.capacity;
        }
        let entry = self.source_indices.len();
        if entry == self.capacity {
            return Err(VisibilityError {
                capacity: self.capacity,
            });
        }
        self.source_indices.push(source_index as u32);
        self.source_next[entry] = usize::MAX;
        let tail = self.bucket_tails[bucket];
        if tail == usize::MAX {
            self.bucket_heads[bucket] = entry;
        } else {
            self.source_next[tail] = entry;
        }
        self.bucket_tails[bucket] = entry;
        Ok(())
    }

    /// Returns the maximum number of visible instances.
    #[must_use]
    pub const fn capacity(&self) -> usize {
        self.capacity
    }

    /// Returns the current number of visible instances.
    #[must_use]
    pub fn len(&self) -> usize {
        self.instances.len()
    }

    /// Returns whether no instance is currently visible.
    #[must_use]
    pub fn is_empty(&self) -> bool {
        self.instances.is_empty()
    }

    /// Returns geometry IDs in grouped visible order.
    #[must_use]
    pub fn geometries(&self) -> &[u32] {
        &self.geometries
    }

    /// Returns pipeline IDs in grouped visible order.
    #[must_use]
    pub fn pipelines(&self) -> &[u32] {
        &self.pipelines
    }

    /// Returns material IDs in grouped visible order.
    #[must_use]
    pub fn materials(&self) -> &[u32] {
        &self.materials
    }

    /// Returns GPU instance records in grouped visible order.
    #[must_use]
    pub fn instances(&self) -> &[GpuInstance] {
        &self.instances
    }

    /// Returns the stable allocation pointer for visible geometry IDs.
    #[must_use]
    pub fn geometries_capacity_ptr(&self) -> *const u32 {
        self.geometries.as_ptr()
    }

    /// Returns the stable allocation pointer for visible pipeline IDs.
    #[must_use]
    pub fn pipelines_capacity_ptr(&self) -> *const u32 {
        self.pipelines.as_ptr()
    }

    /// Returns the stable allocation pointer for visible material IDs.
    #[must_use]
    pub fn materials_capacity_ptr(&self) -> *const u32 {
        self.materials.as_ptr()
    }

    /// Returns the stable allocation pointer for visible GPU instances.
    #[must_use]
    pub fn instances_capacity_ptr(&self) -> *const GpuInstance {
        self.instances.as_ptr()
    }
}

fn hash_render_key(pipeline: u32, material: u32, geometry: u32) -> usize {
    (pipeline.wrapping_mul(0x9e37_79b9)
        ^ material.wrapping_mul(0x85eb_ca6b)
        ^ geometry.wrapping_mul(0xc2b2_ae35)) as usize
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::math::{Mat4, perspective};
    use crate::{Material, MaterialHandle, MeshRenderer, Transform, World, WorldCapacity};

    #[test]
    fn frustum_intersects_inside_sphere_and_rejects_outside_sphere() {
        let mut projection = Mat4::default();
        perspective(&mut projection, 60.0_f32.to_radians(), 1.0, 0.1, 100.0);
        let frustum = Frustum::from_view_projection(&projection);
        assert!(frustum.intersects_sphere([0.0, 0.0, -5.0], 1.0));
        assert!(!frustum.intersects_sphere([100.0, 0.0, -5.0], 1.0));
        assert!(!frustum.intersects_sphere([0.0, 0.0, 5.0], 1.0));
    }

    #[test]
    fn visible_items_are_compacted_and_grouped() {
        let mut world = World::with_capacity(WorldCapacity::default());
        let first_material = world.spawn().unwrap();
        let second_material = world.spawn().unwrap();
        world.add_material(first_material, Material::default());
        world.add_material(second_material, Material::default());
        for (geometry, material) in [
            (2, second_material),
            (1, first_material),
            (2, first_material),
        ] {
            let entity = world.spawn().unwrap();
            world.add_transform(entity, Transform::default());
            world.add_mesh_renderer(
                entity,
                MeshRenderer {
                    geometry,
                    material: MaterialHandle::from_entity(material),
                },
            );
        }
        world.update();
        let mut render_world = RenderWorld::with_capacity(8, 1);
        render_world.extract(&world).unwrap();
        let mut visible = VisibleRenderBuffer::with_capacity(8);
        let stats = visible.cull(&render_world).unwrap();
        assert_eq!(stats.visible, 3);
        assert_eq!(visible.geometries(), &[1, 2, 2]);
        assert_eq!(
            visible.materials(),
            &[
                first_material.raw(),
                first_material.raw(),
                second_material.raw()
            ]
        );
    }
}
